/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#d1e4fb",
        "surface": "#f7f9ff",
        "on-primary-fixed-variant": "#005228",
        "surface-bright": "#f7f9ff",
        "inverse-on-surface": "#e8f2ff",
        "primary-fixed-dim": "#4ae183",
        "on-tertiary-container": "#772e14",
        "primary-container": "#2ecc71",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#454747",
        "tertiary-container": "#ff9875",
        "secondary-container": "#dfe0e0",
        "on-secondary-fixed": "#1a1c1c",
        "inverse-surface": "#203243",
        "secondary": "#5d5f5f",
        "on-primary-container": "#005027",
        "tertiary-fixed-dim": "#ffb59d",
        "surface-container-low": "#edf4ff",
        "on-surface": "#091d2e",
        "outline": "#6c7b6d",
        "secondary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#390c00",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#616363",
        "primary-fixed": "#6bfe9c",
        "surface-container": "#e3efff",
        "surface-tint": "#006d37",
        "surface-container-high": "#d9eaff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#00210c",
        "on-primary": "#ffffff",
        "tertiary": "#98472a",
        "on-error": "#ffffff",
        "background": "#f7f9ff",
        "on-error-container": "#93000a",
        "inverse-primary": "#4ae183",
        "primary": "#006d37",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d1e4fb",
        "on-surface-variant": "#3d4a3e",
        "surface-dim": "#c9dcf3",
        "tertiary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#c6c6c7",
        "on-background": "#091d2e",
        "outline-variant": "#bbcbbb",
        "on-tertiary-fixed-variant": "#793015",
        "accent-orange": "#EA580C",
        "success": "#22C55E",
        "warning": "#F59E0B"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "container-margin": "20px",
        "gutter": "16px",
        "unit": "4px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "title-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "caption": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "title-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-lg": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "caption": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-lg-mobile": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
