// src/theme/colors.ts
export default {
  primary: '#006d37',
  'primary-container': '#2ecc71',
  'on-primary': '#ffffff',
  'on-primary-container': '#005027',
  secondary: '#5d5f5f',
  'secondary-container': '#dfe0e0',
  'on-secondary': '#ffffff',
  'on-secondary-container': '#616363',
  tertiary: '#98472a',
  'tertiary-container': '#ff9875',
  'on-tertiary-container': '#772e14',
  background: '#f7f9ff',
  'on-background': '#091d2e',
  surface: '#f7f9ff',
  'on-surface': '#091d2e',
  'surface-variant': '#d1e4fb',
  'on-surface-variant': '#3d4a3e',
  'surface-container-lowest': '#ffffff',
  'surface-container-low': '#edf4ff',
  'surface-container': '#e3efff',
  'surface-container-high': '#d9eaff',
  'surface-container-highest': '#d1e4fb',
  error: '#ba1a1a',
  'on-error': '#ffffff',
  'error-container': '#ffdad6',
  'on-error-container': '#93000a',
  outline: '#6c7b6d',
  'outline-variant': '#bbcbbb',
  // Preserved from original
  accentOrange: '#EA580C',
  success: '#22C55E',
  warning: '#F59E0B',
};
